//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jcr.Api.Helpers.CCMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.EmailService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailDetails", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.BusinessController")]
    [System.SerializableAttribute()]
    public partial class MailDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmpUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailBCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErUserScheduleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FailedRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> GuidListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtNewEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserEmailScheduleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionTypeID {
            get {
                return this.ActionTypeIDField;
            }
            set {
                if ((this.ActionTypeIDField.Equals(value) != true)) {
                    this.ActionTypeIDField = value;
                    this.RaisePropertyChanged("ActionTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmpUrl {
            get {
                return this.AmpUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AmpUrlField, value) != true)) {
                    this.AmpUrlField = value;
                    this.RaisePropertyChanged("AmpUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode {
            get {
                return this.ApplicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationCodeField, value) != true)) {
                    this.ApplicationCodeField = value;
                    this.RaisePropertyChanged("ApplicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomText {
            get {
                return this.CustomTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomTextField, value) != true)) {
                    this.CustomTextField = value;
                    this.RaisePropertyChanged("CustomText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailBCC {
            get {
                return this.EmailBCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailBCCField, value) != true)) {
                    this.EmailBCCField = value;
                    this.RaisePropertyChanged("EmailBCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCC {
            get {
                return this.EmailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailCCField, value) != true)) {
                    this.EmailCCField = value;
                    this.RaisePropertyChanged("EmailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErUserScheduleID {
            get {
                return this.ErUserScheduleIDField;
            }
            set {
                if ((this.ErUserScheduleIDField.Equals(value) != true)) {
                    this.ErUserScheduleIDField = value;
                    this.RaisePropertyChanged("ErUserScheduleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FailedRecipients {
            get {
                return this.FailedRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedRecipientsField, value) != true)) {
                    this.FailedRecipientsField = value;
                    this.RaisePropertyChanged("FailedRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEmail {
            get {
                return this.FromEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEmailField, value) != true)) {
                    this.FromEmailField = value;
                    this.RaisePropertyChanged("FromEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> GuidList {
            get {
                return this.GuidListField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidListField, value) != true)) {
                    this.GuidListField = value;
                    this.RaisePropertyChanged("GuidList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContent {
            get {
                return this.MailContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MailContentField, value) != true)) {
                    this.MailContentField = value;
                    this.RaisePropertyChanged("MailContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubject {
            get {
                return this.MailSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.MailSubjectField, value) != true)) {
                    this.MailSubjectField = value;
                    this.RaisePropertyChanged("MailSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportName {
            get {
                return this.ReportNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportNameField, value) != true)) {
                    this.ReportNameField = value;
                    this.RaisePropertyChanged("ReportName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateID {
            get {
                return this.TemplateIDField;
            }
            set {
                if ((this.TemplateIDField.Equals(value) != true)) {
                    this.TemplateIDField = value;
                    this.RaisePropertyChanged("TemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtNewEmail {
            get {
                return this.TxtNewEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtNewEmailField, value) != true)) {
                    this.TxtNewEmailField = value;
                    this.RaisePropertyChanged("TxtNewEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserEmailScheduleID {
            get {
                return this.UserEmailScheduleIDField;
            }
            set {
                if ((this.UserEmailScheduleIDField.Equals(value) != true)) {
                    this.UserEmailScheduleIDField = value;
                    this.RaisePropertyChanged("UserEmailScheduleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskMailDetail", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.BusinessController")]
    [System.SerializableAttribute()]
    public partial class TaskMailDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.EmailRecipient> EmailRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMailFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNotificationScheduleIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionTypeID {
            get {
                return this.ActionTypeIDField;
            }
            set {
                if ((this.ActionTypeIDField.Equals(value) != true)) {
                    this.ActionTypeIDField = value;
                    this.RaisePropertyChanged("ActionTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode {
            get {
                return this.ApplicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationCodeField, value) != true)) {
                    this.ApplicationCodeField = value;
                    this.RaisePropertyChanged("ApplicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailLogID {
            get {
                return this.EmailLogIDField;
            }
            set {
                if ((this.EmailLogIDField.Equals(value) != true)) {
                    this.EmailLogIDField = value;
                    this.RaisePropertyChanged("EmailLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.EmailRecipient> EmailRecipients {
            get {
                return this.EmailRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailRecipientsField, value) != true)) {
                    this.EmailRecipientsField = value;
                    this.RaisePropertyChanged("EmailRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEmail {
            get {
                return this.FromEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEmailField, value) != true)) {
                    this.FromEmailField = value;
                    this.RaisePropertyChanged("FromEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMailFailed {
            get {
                return this.IsMailFailedField;
            }
            set {
                if ((this.IsMailFailedField.Equals(value) != true)) {
                    this.IsMailFailedField = value;
                    this.RaisePropertyChanged("IsMailFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskNotificationScheduleIDs {
            get {
                return this.TaskNotificationScheduleIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNotificationScheduleIDsField, value) != true)) {
                    this.TaskNotificationScheduleIDsField = value;
                    this.RaisePropertyChanged("TaskNotificationScheduleIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateID {
            get {
                return this.TemplateIDField;
            }
            set {
                if ((this.TemplateIDField.Equals(value) != true)) {
                    this.TemplateIDField = value;
                    this.RaisePropertyChanged("TemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRecipient", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.BusinessController")]
    [System.SerializableAttribute()]
    public partial class EmailRecipient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMailFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailLogID {
            get {
                return this.EmailLogIDField;
            }
            set {
                if ((this.EmailLogIDField.Equals(value) != true)) {
                    this.EmailLogIDField = value;
                    this.RaisePropertyChanged("EmailLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMailFailed {
            get {
                return this.IsMailFailedField;
            }
            set {
                if ((this.IsMailFailedField.Equals(value) != true)) {
                    this.IsMailFailedField = value;
                    this.RaisePropertyChanged("IsMailFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskDetail", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.BusinessController")]
    [System.SerializableAttribute()]
    public partial class TaskDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompletionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompletionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HCOIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemAssociatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskLinkUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFullNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedBy {
            get {
                return this.AssignedByField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedByField, value) != true)) {
                    this.AssignedByField = value;
                    this.RaisePropertyChanged("AssignedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedOn {
            get {
                return this.AssignedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedOnField, value) != true)) {
                    this.AssignedOnField = value;
                    this.RaisePropertyChanged("AssignedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedToField, value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompletionDate {
            get {
                return this.CompletionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CompletionDateField, value) != true)) {
                    this.CompletionDateField = value;
                    this.RaisePropertyChanged("CompletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompletionDetails {
            get {
                return this.CompletionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompletionDetailsField, value) != true)) {
                    this.CompletionDetailsField = value;
                    this.RaisePropertyChanged("CompletionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCOID {
            get {
                return this.HCOIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HCOIDField, value) != true)) {
                    this.HCOIDField = value;
                    this.RaisePropertyChanged("HCOID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemAssociated {
            get {
                return this.ItemAssociatedField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemAssociatedField, value) != true)) {
                    this.ItemAssociatedField = value;
                    this.RaisePropertyChanged("ItemAssociated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskDetails {
            get {
                return this.TaskDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskDetailsField, value) != true)) {
                    this.TaskDetailsField = value;
                    this.RaisePropertyChanged("TaskDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskIDs {
            get {
                return this.TaskIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDsField, value) != true)) {
                    this.TaskIDsField = value;
                    this.RaisePropertyChanged("TaskIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskLinkUrl {
            get {
                return this.TaskLinkUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskLinkUrlField, value) != true)) {
                    this.TaskLinkUrlField = value;
                    this.RaisePropertyChanged("TaskLinkUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskStatus {
            get {
                return this.TaskStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskStatusField, value) != true)) {
                    this.TaskStatusField = value;
                    this.RaisePropertyChanged("TaskStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFullName {
            get {
                return this.UserFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFullNameField, value) != true)) {
                    this.UserFullNameField = value;
                    this.RaisePropertyChanged("UserFullName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCMService.IProcessEmail")]
    public interface IProcessEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetData", ReplyAction="http://tempuri.org/IProcessEmail/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetData", ReplyAction="http://tempuri.org/IProcessEmail/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProcessEmail/GetDataUsingDataContractResponse")]
        Jcr.Api.Helpers.CCMService.CompositeType GetDataUsingDataContract(Jcr.Api.Helpers.CCMService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProcessEmail/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.CompositeType> GetDataUsingDataContractAsync(Jcr.Api.Helpers.CCMService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEmailResponse")]
        Jcr.Api.Helpers.CCMService.SendEmailResponse SendEmail(Jcr.Api.Helpers.CCMService.SendEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendEmailResponse> SendEmailAsync(Jcr.Api.Helpers.CCMService.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEREmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEREmailResponse")]
        Jcr.Api.Helpers.CCMService.SendEREmailResponse SendEREmail(Jcr.Api.Helpers.CCMService.SendEREmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEREmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEREmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendEREmailResponse> SendEREmailAsync(Jcr.Api.Helpers.CCMService.SendEREmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetTokenReplacementText", ReplyAction="http://tempuri.org/IProcessEmail/GetTokenReplacementTextResponse")]
        string GetTokenReplacementText(string token, int SiteID, int templateID, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetTokenReplacementText", ReplyAction="http://tempuri.org/IProcessEmail/GetTokenReplacementTextResponse")]
        System.Threading.Tasks.Task<string> GetTokenReplacementTextAsync(string token, int SiteID, int templateID, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendAdhocEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendAdhocEmailResponse")]
        Jcr.Api.Helpers.CCMService.SendAdhocEmailResponse SendAdhocEmail(Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendAdhocEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendAdhocEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendAdhocEmailResponse> SendAdhocEmailAsync(Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/ProcessText", ReplyAction="http://tempuri.org/IProcessEmail/ProcessTextResponse")]
        string ProcessText(int SiteID, int templateID, string templateText, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/ProcessText", ReplyAction="http://tempuri.org/IProcessEmail/ProcessTextResponse")]
        System.Threading.Tasks.Task<string> ProcessTextAsync(int SiteID, int templateID, string templateText, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendGeneralEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendGeneralEmailResponse")]
        Jcr.Api.Helpers.CCMService.SendGeneralEmailResponse SendGeneralEmail(Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendGeneralEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendGeneralEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendGeneralEmailResponse> SendGeneralEmailAsync(Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendOversizeEmailAlert", ReplyAction="http://tempuri.org/IProcessEmail/SendOversizeEmailAlertResponse")]
        int SendOversizeEmailAlert(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendOversizeEmailAlert", ReplyAction="http://tempuri.org/IProcessEmail/SendOversizeEmailAlertResponse")]
        System.Threading.Tasks.Task<int> SendOversizeEmailAlertAsync(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmailResponse")]
        Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailResponse SendTracerDeptAssignmentEmail(Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailResponse> SendTracerDeptAssignmentEmailAsync(Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTaskEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTaskEmailResponse")]
        Jcr.Api.Helpers.CCMService.TaskMailDetail SendTaskEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.TaskDetail taskDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTaskEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTaskEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.TaskMailDetail> SendTaskEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.TaskDetail taskDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTaskNotificationEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTaskNotificationEmailResponse")]
        Jcr.Api.Helpers.CCMService.EmailRecipient SendTaskNotificationEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.EmailRecipient emailRecipient, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTaskNotificationEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTaskNotificationEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.EmailRecipient> SendTaskNotificationEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.EmailRecipient emailRecipient, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTasksEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTasksEmailResponse")]
        Jcr.Api.Helpers.CCMService.TaskMailDetail SendTasksEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTasksEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTasksEmailResponse")]
        System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.TaskMailDetail> SendTasksEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Collections.Generic.List<string> attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int createdByUserId;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(int SiteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, string fnReturnValue, int createdByUserId) {
            this.SiteID = SiteID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.fnReturnValue = fnReturnValue;
            this.createdByUserId = createdByUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(int SendEmailResult, string fnReturnValue) {
            this.SendEmailResult = SendEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEREmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEREmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ERReportUserScheduleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int siteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Collections.Generic.List<string> attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string functionReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string fromEmail;
        
        public SendEREmailRequest() {
        }
        
        public SendEREmailRequest(int ERReportUserScheduleID, int siteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, string functionReturnValue, int createdByUserId, string fromEmail) {
            this.ERReportUserScheduleID = ERReportUserScheduleID;
            this.siteID = siteID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.functionReturnValue = functionReturnValue;
            this.createdByUserId = createdByUserId;
            this.fromEmail = fromEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEREmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEREmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendEREmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string functionReturnValue;
        
        public SendEREmailResponse() {
        }
        
        public SendEREmailResponse(int SendEREmailResult, string functionReturnValue) {
            this.SendEREmailResult = SendEREmailResult;
            this.functionReturnValue = functionReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAdhocEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAdhocEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ToEMailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CCEMailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string txtEmailSubject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string txtNewEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public System.Collections.Generic.List<string> attachments;
        
        public SendAdhocEmailRequest() {
        }
        
        public SendAdhocEmailRequest(int SiteID, int templateID, string ToEMailAddress, string CCEMailAddress, string applicationCode, int actionTypeID, string fnReturnValue, int createdByUserId, string txtEmailSubject, string txtNewEmail, System.Collections.Generic.List<string> attachments) {
            this.SiteID = SiteID;
            this.templateID = templateID;
            this.ToEMailAddress = ToEMailAddress;
            this.CCEMailAddress = CCEMailAddress;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.fnReturnValue = fnReturnValue;
            this.createdByUserId = createdByUserId;
            this.txtEmailSubject = txtEmailSubject;
            this.txtNewEmail = txtNewEmail;
            this.attachments = attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAdhocEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAdhocEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendAdhocEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendAdhocEmailResponse() {
        }
        
        public SendAdhocEmailResponse(int SendAdhocEmailResult, string fnReturnValue) {
            this.SendAdhocEmailResult = SendAdhocEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGeneralEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGeneralEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Jcr.Api.Helpers.CCMService.MailDetails mailDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int createdByUserId;
        
        public SendGeneralEmailRequest() {
        }
        
        public SendGeneralEmailRequest(Jcr.Api.Helpers.CCMService.MailDetails mailDetails, string fnReturnValue, string applicationCode, int actionTypeID, int createdByUserId) {
            this.mailDetails = mailDetails;
            this.fnReturnValue = fnReturnValue;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.createdByUserId = createdByUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGeneralEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGeneralEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendGeneralEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendGeneralEmailResponse() {
        }
        
        public SendGeneralEmailResponse(int SendGeneralEmailResult, string fnReturnValue) {
            this.SendGeneralEmailResult = SendGeneralEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTracerDeptAssignmentEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTracerDeptAssignmentEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int siteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userEmailScheduleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Collections.Generic.List<string> attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string functionReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string fromEmail;
        
        public SendTracerDeptAssignmentEmailRequest() {
        }
        
        public SendTracerDeptAssignmentEmailRequest(int siteID, int userEmailScheduleID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, string functionReturnValue, int createdByUserId, string fromEmail) {
            this.siteID = siteID;
            this.userEmailScheduleID = userEmailScheduleID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.functionReturnValue = functionReturnValue;
            this.createdByUserId = createdByUserId;
            this.fromEmail = fromEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTracerDeptAssignmentEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTracerDeptAssignmentEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendTracerDeptAssignmentEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string functionReturnValue;
        
        public SendTracerDeptAssignmentEmailResponse() {
        }
        
        public SendTracerDeptAssignmentEmailResponse(int SendTracerDeptAssignmentEmailResult, string functionReturnValue) {
            this.SendTracerDeptAssignmentEmailResult = SendTracerDeptAssignmentEmailResult;
            this.functionReturnValue = functionReturnValue;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessEmailChannel : Jcr.Api.Helpers.CCMService.IProcessEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessEmailClient : System.ServiceModel.ClientBase<Jcr.Api.Helpers.CCMService.IProcessEmail>, Jcr.Api.Helpers.CCMService.IProcessEmail {
        
        public ProcessEmailClient() {
        }
        
        public ProcessEmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessEmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessEmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessEmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Jcr.Api.Helpers.CCMService.CompositeType GetDataUsingDataContract(Jcr.Api.Helpers.CCMService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.CompositeType> GetDataUsingDataContractAsync(Jcr.Api.Helpers.CCMService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jcr.Api.Helpers.CCMService.SendEmailResponse Jcr.Api.Helpers.CCMService.IProcessEmail.SendEmail(Jcr.Api.Helpers.CCMService.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public int SendEmail(int SiteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, ref string fnReturnValue, int createdByUserId) {
            Jcr.Api.Helpers.CCMService.SendEmailRequest inValue = new Jcr.Api.Helpers.CCMService.SendEmailRequest();
            inValue.SiteID = SiteID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.fnReturnValue = fnReturnValue;
            inValue.createdByUserId = createdByUserId;
            Jcr.Api.Helpers.CCMService.SendEmailResponse retVal = ((Jcr.Api.Helpers.CCMService.IProcessEmail)(this)).SendEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendEmailResult;
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendEmailResponse> SendEmailAsync(Jcr.Api.Helpers.CCMService.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jcr.Api.Helpers.CCMService.SendEREmailResponse Jcr.Api.Helpers.CCMService.IProcessEmail.SendEREmail(Jcr.Api.Helpers.CCMService.SendEREmailRequest request) {
            return base.Channel.SendEREmail(request);
        }
        
        public int SendEREmail(int ERReportUserScheduleID, int siteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, ref string functionReturnValue, int createdByUserId, string fromEmail) {
            Jcr.Api.Helpers.CCMService.SendEREmailRequest inValue = new Jcr.Api.Helpers.CCMService.SendEREmailRequest();
            inValue.ERReportUserScheduleID = ERReportUserScheduleID;
            inValue.siteID = siteID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.functionReturnValue = functionReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.fromEmail = fromEmail;
            Jcr.Api.Helpers.CCMService.SendEREmailResponse retVal = ((Jcr.Api.Helpers.CCMService.IProcessEmail)(this)).SendEREmail(inValue);
            functionReturnValue = retVal.functionReturnValue;
            return retVal.SendEREmailResult;
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendEREmailResponse> SendEREmailAsync(Jcr.Api.Helpers.CCMService.SendEREmailRequest request) {
            return base.Channel.SendEREmailAsync(request);
        }
        
        public string GetTokenReplacementText(string token, int SiteID, int templateID, bool isBlankOK) {
            return base.Channel.GetTokenReplacementText(token, SiteID, templateID, isBlankOK);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenReplacementTextAsync(string token, int SiteID, int templateID, bool isBlankOK) {
            return base.Channel.GetTokenReplacementTextAsync(token, SiteID, templateID, isBlankOK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jcr.Api.Helpers.CCMService.SendAdhocEmailResponse Jcr.Api.Helpers.CCMService.IProcessEmail.SendAdhocEmail(Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest request) {
            return base.Channel.SendAdhocEmail(request);
        }
        
        public int SendAdhocEmail(int SiteID, int templateID, string ToEMailAddress, string CCEMailAddress, string applicationCode, int actionTypeID, ref string fnReturnValue, int createdByUserId, string txtEmailSubject, string txtNewEmail, System.Collections.Generic.List<string> attachments) {
            Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest inValue = new Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest();
            inValue.SiteID = SiteID;
            inValue.templateID = templateID;
            inValue.ToEMailAddress = ToEMailAddress;
            inValue.CCEMailAddress = CCEMailAddress;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.fnReturnValue = fnReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.txtEmailSubject = txtEmailSubject;
            inValue.txtNewEmail = txtNewEmail;
            inValue.attachments = attachments;
            Jcr.Api.Helpers.CCMService.SendAdhocEmailResponse retVal = ((Jcr.Api.Helpers.CCMService.IProcessEmail)(this)).SendAdhocEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendAdhocEmailResult;
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendAdhocEmailResponse> SendAdhocEmailAsync(Jcr.Api.Helpers.CCMService.SendAdhocEmailRequest request) {
            return base.Channel.SendAdhocEmailAsync(request);
        }
        
        public string ProcessText(int SiteID, int templateID, string templateText, bool isBlankOK) {
            return base.Channel.ProcessText(SiteID, templateID, templateText, isBlankOK);
        }
        
        public System.Threading.Tasks.Task<string> ProcessTextAsync(int SiteID, int templateID, string templateText, bool isBlankOK) {
            return base.Channel.ProcessTextAsync(SiteID, templateID, templateText, isBlankOK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jcr.Api.Helpers.CCMService.SendGeneralEmailResponse Jcr.Api.Helpers.CCMService.IProcessEmail.SendGeneralEmail(Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest request) {
            return base.Channel.SendGeneralEmail(request);
        }
        
        public int SendGeneralEmail(Jcr.Api.Helpers.CCMService.MailDetails mailDetails, ref string fnReturnValue, string applicationCode, int actionTypeID, int createdByUserId) {
            Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest inValue = new Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest();
            inValue.mailDetails = mailDetails;
            inValue.fnReturnValue = fnReturnValue;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.createdByUserId = createdByUserId;
            Jcr.Api.Helpers.CCMService.SendGeneralEmailResponse retVal = ((Jcr.Api.Helpers.CCMService.IProcessEmail)(this)).SendGeneralEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendGeneralEmailResult;
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendGeneralEmailResponse> SendGeneralEmailAsync(Jcr.Api.Helpers.CCMService.SendGeneralEmailRequest request) {
            return base.Channel.SendGeneralEmailAsync(request);
        }
        
        public int SendOversizeEmailAlert(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId) {
            return base.Channel.SendOversizeEmailAlert(subject, siteID, userID, reportName, applicationCode, actionTypeID, erReportSchedule, createdByUserId);
        }
        
        public System.Threading.Tasks.Task<int> SendOversizeEmailAlertAsync(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId) {
            return base.Channel.SendOversizeEmailAlertAsync(subject, siteID, userID, reportName, applicationCode, actionTypeID, erReportSchedule, createdByUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailResponse Jcr.Api.Helpers.CCMService.IProcessEmail.SendTracerDeptAssignmentEmail(Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest request) {
            return base.Channel.SendTracerDeptAssignmentEmail(request);
        }
        
        public int SendTracerDeptAssignmentEmail(int siteID, int userEmailScheduleID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, ref string functionReturnValue, int createdByUserId, string fromEmail) {
            Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest inValue = new Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest();
            inValue.siteID = siteID;
            inValue.userEmailScheduleID = userEmailScheduleID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.functionReturnValue = functionReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.fromEmail = fromEmail;
            Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailResponse retVal = ((Jcr.Api.Helpers.CCMService.IProcessEmail)(this)).SendTracerDeptAssignmentEmail(inValue);
            functionReturnValue = retVal.functionReturnValue;
            return retVal.SendTracerDeptAssignmentEmailResult;
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailResponse> SendTracerDeptAssignmentEmailAsync(Jcr.Api.Helpers.CCMService.SendTracerDeptAssignmentEmailRequest request) {
            return base.Channel.SendTracerDeptAssignmentEmailAsync(request);
        }
        
        public Jcr.Api.Helpers.CCMService.TaskMailDetail SendTaskEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.TaskDetail taskDetail) {
            return base.Channel.SendTaskEmail(taskMailDetail, taskDetail);
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.TaskMailDetail> SendTaskEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.TaskDetail taskDetail) {
            return base.Channel.SendTaskEmailAsync(taskMailDetail, taskDetail);
        }
        
        public Jcr.Api.Helpers.CCMService.EmailRecipient SendTaskNotificationEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.EmailRecipient emailRecipient, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails) {
            return base.Channel.SendTaskNotificationEmail(taskMailDetail, emailRecipient, taskDetails);
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.EmailRecipient> SendTaskNotificationEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, Jcr.Api.Helpers.CCMService.EmailRecipient emailRecipient, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails) {
            return base.Channel.SendTaskNotificationEmailAsync(taskMailDetail, emailRecipient, taskDetails);
        }
        
        public Jcr.Api.Helpers.CCMService.TaskMailDetail SendTasksEmail(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails) {
            return base.Channel.SendTasksEmail(taskMailDetail, taskDetails);
        }
        
        public System.Threading.Tasks.Task<Jcr.Api.Helpers.CCMService.TaskMailDetail> SendTasksEmailAsync(Jcr.Api.Helpers.CCMService.TaskMailDetail taskMailDetail, System.Collections.Generic.List<Jcr.Api.Helpers.CCMService.TaskDetail> taskDetails) {
            return base.Channel.SendTasksEmailAsync(taskMailDetail, taskDetails);
        }
    }
}
