// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{
    using Jcr.Data;

    public interface IDBMEdition01Context : System.IDisposable
    {

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<ApiAllChildrenMatchParentReturnModel> ApiAllChildrenMatchParent(int? tracerId);
        System.Collections.Generic.List<ApiAllChildrenMatchParentReturnModel> ApiAllChildrenMatchParent(int? tracerId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiAllChildrenMatchParentReturnModel>> ApiAllChildrenMatchParentAsync(int? tracerId);

        System.Collections.Generic.List<ApiChangeMasterSiteReturnModel> ApiChangeMasterSite(int? tracerId, int? siteId, int? userId);
        System.Collections.Generic.List<ApiChangeMasterSiteReturnModel> ApiChangeMasterSite(int? tracerId, int? siteId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiChangeMasterSiteReturnModel>> ApiChangeMasterSiteAsync(int? tracerId, int? siteId, int? userId);

        System.Collections.Generic.List<ApiCreateGuestUserByEmailIdsReturnModel> ApiCreateGuestUserByEmailIds(string lstUserEmailIDs, int? siteId, string firstName, string lastName, string middleName, int? externalUserRoleTypeId, int? updatedById);
        System.Collections.Generic.List<ApiCreateGuestUserByEmailIdsReturnModel> ApiCreateGuestUserByEmailIds(string lstUserEmailIDs, int? siteId, string firstName, string lastName, string middleName, int? externalUserRoleTypeId, int? updatedById, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiCreateGuestUserByEmailIdsReturnModel>> ApiCreateGuestUserByEmailIdsAsync(string lstUserEmailIDs, int? siteId, string firstName, string lastName, string middleName, int? externalUserRoleTypeId, int? updatedById);

        int ApiDeleteTask(string taskId);
        // ApiDeleteTaskAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiDeleteTracerCategoryReturnModel> ApiDeleteTracerCategory(int? tracerCategoryId, int? siteId, int? updatedById, int? newTracerCategoryId);
        System.Collections.Generic.List<ApiDeleteTracerCategoryReturnModel> ApiDeleteTracerCategory(int? tracerCategoryId, int? siteId, int? updatedById, int? newTracerCategoryId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiDeleteTracerCategoryReturnModel>> ApiDeleteTracerCategoryAsync(int? tracerCategoryId, int? siteId, int? updatedById, int? newTracerCategoryId);

        int ApiDeleteTracerImageByName(int? tracerCustomId, int? tracerQuestionId, int? tracerResponseId, int? userId, string imageName);
        // ApiDeleteTracerImageByNameAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiDeleteTracerImagesTemp(int? tracerCustomId, int? userId);
        // ApiDeleteTracerImagesTempAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiDisableTaskNotificationSchedules(int? updateTypeId, int? siteId, int? userId, string taskIDs);
        // ApiDisableTaskNotificationSchedulesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiEmailUpdateErReportUserSchedule(int? siteId, bool? sendTaskReport, int? scheduleTypeId, string userTaskRecipients, int? userId, int? updatedUserId, int? taskTypeId);
        // ApiEmailUpdateErReportUserScheduleAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiGetActiveDeptCountReturnModel> ApiGetActiveDeptCount(int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetActiveDeptCountReturnModel> ApiGetActiveDeptCount(int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetActiveDeptCountReturnModel>> ApiGetActiveDeptCountAsync(int? siteId, int? programId);

        System.Collections.Generic.List<ApiGetAmpTaskListByEpTextIdReturnModel> ApiGetAmpTaskListByEpTextId(string standardEffDate, int? siteId, int? programId, int? epTextId);
        System.Collections.Generic.List<ApiGetAmpTaskListByEpTextIdReturnModel> ApiGetAmpTaskListByEpTextId(string standardEffDate, int? siteId, int? programId, int? epTextId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetAmpTaskListByEpTextIdReturnModel>> ApiGetAmpTaskListByEpTextIdAsync(string standardEffDate, int? siteId, int? programId, int? epTextId);

        System.Collections.Generic.List<ApiGetCategoryNamesReturnModel> ApiGetCategoryNames(int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetCategoryNamesReturnModel> ApiGetCategoryNames(int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetCategoryNamesReturnModel>> ApiGetCategoryNamesAsync(int? siteId, int? programId);

        System.Collections.Generic.List<ApiGetChaptersBySiteAndProgramReturnModel> ApiGetChaptersBySiteAndProgram(int? siteId, int? programId, int? userId, int? certificationItemId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId);
        System.Collections.Generic.List<ApiGetChaptersBySiteAndProgramReturnModel> ApiGetChaptersBySiteAndProgram(int? siteId, int? programId, int? userId, int? certificationItemId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetChaptersBySiteAndProgramReturnModel>> ApiGetChaptersBySiteAndProgramAsync(int? siteId, int? programId, int? userId, int? certificationItemId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId);

        System.Collections.Generic.List<ApiGetChapterStandardByEpTextIdReturnModel> ApiGetChapterStandardByEpTextId(string standardEffBeginDate, int? epTextId, int? programId);
        System.Collections.Generic.List<ApiGetChapterStandardByEpTextIdReturnModel> ApiGetChapterStandardByEpTextId(string standardEffBeginDate, int? epTextId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetChapterStandardByEpTextIdReturnModel>> ApiGetChapterStandardByEpTextIdAsync(string standardEffBeginDate, int? epTextId, int? programId);

        System.Collections.Generic.List<ApiGetCmsTaskListByCmsStandardIdReturnModel> ApiGetCmsTaskListByCmsStandardId(string standardEffDate, int? siteId, int? programId, int? cmsStandardId);
        System.Collections.Generic.List<ApiGetCmsTaskListByCmsStandardIdReturnModel> ApiGetCmsTaskListByCmsStandardId(string standardEffDate, int? siteId, int? programId, int? cmsStandardId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetCmsTaskListByCmsStandardIdReturnModel>> ApiGetCmsTaskListByCmsStandardIdAsync(string standardEffDate, int? siteId, int? programId, int? cmsStandardId);

        System.Collections.Generic.List<ApiGetCopDataReturnModel> ApiGetCopData(int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetCopDataReturnModel> ApiGetCopData(int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetCopDataReturnModel>> ApiGetCopDataAsync(int? siteId, int? programId);

        System.Collections.Generic.List<ApiGetCopTagByCmsStandardIdReturnModel> ApiGetCopTagByCmsStandardId(int? programId, int? cmsStandardId);
        System.Collections.Generic.List<ApiGetCopTagByCmsStandardIdReturnModel> ApiGetCopTagByCmsStandardId(int? programId, int? cmsStandardId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetCopTagByCmsStandardIdReturnModel>> ApiGetCopTagByCmsStandardIdAsync(int? programId, int? cmsStandardId);

        System.Collections.Generic.List<ApiGetDepartmentHierarchyByRankIdReturnModel> ApiGetDepartmentHierarchyByRankId(int? siteId, int? programId, int? rankId, bool? isCategoryActive, bool? isCategoryItemActive);
        System.Collections.Generic.List<ApiGetDepartmentHierarchyByRankIdReturnModel> ApiGetDepartmentHierarchyByRankId(int? siteId, int? programId, int? rankId, bool? isCategoryActive, bool? isCategoryItemActive, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetDepartmentHierarchyByRankIdReturnModel>> ApiGetDepartmentHierarchyByRankIdAsync(int? siteId, int? programId, int? rankId, bool? isCategoryActive, bool? isCategoryItemActive);

        System.Collections.Generic.List<ApiGetElementsByTagReturnModel> ApiGetElementsByTag(int? programId, string tagCode);
        System.Collections.Generic.List<ApiGetElementsByTagReturnModel> ApiGetElementsByTag(int? programId, string tagCode, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetElementsByTagReturnModel>> ApiGetElementsByTagAsync(int? programId, string tagCode);

        System.Collections.Generic.List<ApiGetEPsByStandardReturnModel> ApiGetEPsByStandard(int? userId, int? productType, int? siteId, int? programId, int? standardTextId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId, int? certificationItemId);
        System.Collections.Generic.List<ApiGetEPsByStandardReturnModel> ApiGetEPsByStandard(int? userId, int? productType, int? siteId, int? programId, int? standardTextId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId, int? certificationItemId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetEPsByStandardReturnModel>> ApiGetEPsByStandardAsync(int? userId, int? productType, int? siteId, int? programId, int? standardTextId, System.DateTime? standardEffBeginDate, int? serviceProfileTypeId, int? certificationItemId);

        System.Collections.Generic.List<ApiGetFileStreamIDbyFileDisplayNameReturnModel> ApiGetFileStreamIDbyFileDisplayName(string fileDisplayText);
        System.Collections.Generic.List<ApiGetFileStreamIDbyFileDisplayNameReturnModel> ApiGetFileStreamIDbyFileDisplayName(string fileDisplayText, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetFileStreamIDbyFileDisplayNameReturnModel>> ApiGetFileStreamIDbyFileDisplayNameAsync(string fileDisplayText);

        int ApiGetLabelForUnassigned(out string labelOfTheDay);
        // ApiGetLabelForUnassignedAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiGetLicenseDetailsForGuestLinkReturnModel> ApiGetLicenseDetailsForGuestLink(int? guestLinkId);
        System.Collections.Generic.List<ApiGetLicenseDetailsForGuestLinkReturnModel> ApiGetLicenseDetailsForGuestLink(int? guestLinkId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetLicenseDetailsForGuestLinkReturnModel>> ApiGetLicenseDetailsForGuestLinkAsync(int? guestLinkId);

        System.Collections.Generic.List<ApiGetMaxTaskAssignedDateReturnModel> ApiGetMaxTaskAssignedDate(string lstTaskIDs);
        System.Collections.Generic.List<ApiGetMaxTaskAssignedDateReturnModel> ApiGetMaxTaskAssignedDate(string lstTaskIDs, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetMaxTaskAssignedDateReturnModel>> ApiGetMaxTaskAssignedDateAsync(string lstTaskIDs);

        System.Collections.Generic.List<ApiGetMobileTracerHeaderReturnModel> ApiGetMobileTracerHeader(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetMobileTracerHeaderReturnModel> ApiGetMobileTracerHeader(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetMobileTracerHeaderReturnModel>> ApiGetMobileTracerHeaderAsync(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId);

        System.Collections.Generic.List<ApiGetParentDetailsForLockedTracerCategoryReturnModel> ApiGetParentDetailsForLockedTracerCategory(int? tracerCategoryId);
        System.Collections.Generic.List<ApiGetParentDetailsForLockedTracerCategoryReturnModel> ApiGetParentDetailsForLockedTracerCategory(int? tracerCategoryId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetParentDetailsForLockedTracerCategoryReturnModel>> ApiGetParentDetailsForLockedTracerCategoryAsync(int? tracerCategoryId);

        System.Collections.Generic.List<ApiGetPasswordResetIntervalReturnModel> ApiGetPasswordResetInterval(int? userId);
        System.Collections.Generic.List<ApiGetPasswordResetIntervalReturnModel> ApiGetPasswordResetInterval(int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetPasswordResetIntervalReturnModel>> ApiGetPasswordResetIntervalAsync(int? userId);

        System.Collections.Generic.List<ApiGetProgramsBySiteReturnModel> ApiGetProgramsBySite(int? siteId);
        System.Collections.Generic.List<ApiGetProgramsBySiteReturnModel> ApiGetProgramsBySite(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetProgramsBySiteReturnModel>> ApiGetProgramsBySiteAsync(int? siteId);

        ApiGetQuestionAnswerImagesReturnModel ApiGetQuestionAnswerImages(int? tracerQuestionId, int? tracerResponseId, int? userId);
        System.Threading.Tasks.Task<ApiGetQuestionAnswerImagesReturnModel> ApiGetQuestionAnswerImagesAsync(int? tracerQuestionId, int? tracerResponseId, int? userId);

        System.Collections.Generic.List<ApiGetSiteEmailNotificationSettingsReturnModel> ApiGetSiteEmailNotificationSettings(int? siteId);
        System.Collections.Generic.List<ApiGetSiteEmailNotificationSettingsReturnModel> ApiGetSiteEmailNotificationSettings(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetSiteEmailNotificationSettingsReturnModel>> ApiGetSiteEmailNotificationSettingsAsync(int? siteId);

        System.Collections.Generic.List<ApiGetStandardsByChapterReturnModel> ApiGetStandardsByChapter(string standardEffBeginDate, int? productType, int? programId, int? chapterId, int? siteId, int? userId, int? serviceProfileTypeId, int? certificationItemId);
        System.Collections.Generic.List<ApiGetStandardsByChapterReturnModel> ApiGetStandardsByChapter(string standardEffBeginDate, int? productType, int? programId, int? chapterId, int? siteId, int? userId, int? serviceProfileTypeId, int? certificationItemId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetStandardsByChapterReturnModel>> ApiGetStandardsByChapterAsync(string standardEffBeginDate, int? productType, int? programId, int? chapterId, int? siteId, int? userId, int? serviceProfileTypeId, int? certificationItemId);

        System.Collections.Generic.List<ApiGetStdDetailsByTracerQuestionReturnModel> ApiGetStdDetailsByTracerQuestion(int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, bool? isGuestAccess);
        System.Collections.Generic.List<ApiGetStdDetailsByTracerQuestionReturnModel> ApiGetStdDetailsByTracerQuestion(int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, bool? isGuestAccess, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetStdDetailsByTracerQuestionReturnModel>> ApiGetStdDetailsByTracerQuestionAsync(int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, bool? isGuestAccess);

        System.Collections.Generic.List<ApiGetSystemTracerInfoReturnModel> ApiGetSystemTracerInfo(int? tracerId, int? userId);
        System.Collections.Generic.List<ApiGetSystemTracerInfoReturnModel> ApiGetSystemTracerInfo(int? tracerId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetSystemTracerInfoReturnModel>> ApiGetSystemTracerInfoAsync(int? tracerId, int? userId);

        System.Collections.Generic.List<ApiGetTagsByCoPReturnModel> ApiGetTagsByCoP(int? programId, string copName);
        System.Collections.Generic.List<ApiGetTagsByCoPReturnModel> ApiGetTagsByCoP(int? programId, string copName, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTagsByCoPReturnModel>> ApiGetTagsByCoPAsync(int? programId, string copName);

        System.Collections.Generic.List<ApiGetTargetSitesForCopyReturnModel> ApiGetTargetSitesForCopy(int? tracerCustomId, int? userId);
        System.Collections.Generic.List<ApiGetTargetSitesForCopyReturnModel> ApiGetTargetSitesForCopy(int? tracerCustomId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTargetSitesForCopyReturnModel>> ApiGetTargetSitesForCopyAsync(int? tracerCustomId, int? userId);

        System.Collections.Generic.List<ApiGetTargetSitesForDeleteReturnModel> ApiGetTargetSitesForDelete(int? tracerCustomId, int? userId);
        System.Collections.Generic.List<ApiGetTargetSitesForDeleteReturnModel> ApiGetTargetSitesForDelete(int? tracerCustomId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTargetSitesForDeleteReturnModel>> ApiGetTargetSitesForDeleteAsync(int? tracerCustomId, int? userId);

        System.Collections.Generic.List<ApiGetTaskDetailsReturnModel> ApiGetTaskDetails(int? taskId, System.DateTime? standardEffDate, int? programId);
        System.Collections.Generic.List<ApiGetTaskDetailsReturnModel> ApiGetTaskDetails(int? taskId, System.DateTime? standardEffDate, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTaskDetailsReturnModel>> ApiGetTaskDetailsAsync(int? taskId, System.DateTime? standardEffDate, int? programId);

        System.Collections.Generic.List<ApiGetTaskDetailsForSendingEmailReturnModel> ApiGetTaskDetailsForSendingEmail(string taskIDs, int? siteId, int? programId, int? userId, string tracersTaskUrl, bool? skipItemAssociated);
        System.Collections.Generic.List<ApiGetTaskDetailsForSendingEmailReturnModel> ApiGetTaskDetailsForSendingEmail(string taskIDs, int? siteId, int? programId, int? userId, string tracersTaskUrl, bool? skipItemAssociated, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTaskDetailsForSendingEmailReturnModel>> ApiGetTaskDetailsForSendingEmailAsync(string taskIDs, int? siteId, int? programId, int? userId, string tracersTaskUrl, bool? skipItemAssociated);

        System.Collections.Generic.List<ApiGetTaskFollowUpRemainderSettingsReturnModel> ApiGetTaskFollowUpRemainderSettings(int? siteId);
        System.Collections.Generic.List<ApiGetTaskFollowUpRemainderSettingsReturnModel> ApiGetTaskFollowUpRemainderSettings(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTaskFollowUpRemainderSettingsReturnModel>> ApiGetTaskFollowUpRemainderSettingsAsync(int? siteId);

        System.Collections.Generic.List<ApiGetTaskLinkDetailsReturnModel> ApiGetTaskLinkDetails(System.Guid? taskLinkGuid);
        System.Collections.Generic.List<ApiGetTaskLinkDetailsReturnModel> ApiGetTaskLinkDetails(System.Guid? taskLinkGuid, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTaskLinkDetailsReturnModel>> ApiGetTaskLinkDetailsAsync(System.Guid? taskLinkGuid);

        System.Collections.Generic.List<ApiGetTaskListReturnModel> ApiGetTaskList(string standardEffDate, int? siteId, int? programId, int? assignedToUserId, int? assignedByUserId);
        System.Collections.Generic.List<ApiGetTaskListReturnModel> ApiGetTaskList(string standardEffDate, int? siteId, int? programId, int? assignedToUserId, int? assignedByUserId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTaskListReturnModel>> ApiGetTaskListAsync(string standardEffDate, int? siteId, int? programId, int? assignedToUserId, int? assignedByUserId);

        System.Collections.Generic.List<ApiGetTracerByIdReturnModel> ApiGetTracerById(int? tracerCustomId);
        System.Collections.Generic.List<ApiGetTracerByIdReturnModel> ApiGetTracerById(int? tracerCustomId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerByIdReturnModel>> ApiGetTracerByIdAsync(int? tracerCustomId);

        System.Collections.Generic.List<ApiGetTracerCategoryBySiteIdReturnModel> ApiGetTracerCategoryBySiteId(int? siteId);
        System.Collections.Generic.List<ApiGetTracerCategoryBySiteIdReturnModel> ApiGetTracerCategoryBySiteId(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerCategoryBySiteIdReturnModel>> ApiGetTracerCategoryBySiteIdAsync(int? siteId);

        System.Collections.Generic.List<ApiGetTracerCategoryNamesReturnModel> ApiGetTracerCategoryNames(int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetTracerCategoryNamesReturnModel> ApiGetTracerCategoryNames(int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerCategoryNamesReturnModel>> ApiGetTracerCategoryNamesAsync(int? siteId, int? programId);

        System.Collections.Generic.List<ApiGetTracerHeaderReturnModel> ApiGetTracerHeader(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId);
        System.Collections.Generic.List<ApiGetTracerHeaderReturnModel> ApiGetTracerHeader(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerHeaderReturnModel>> ApiGetTracerHeaderAsync(int? tracerCustomId, int? tracerResponseId, int? siteId, int? programId);

        int ApiGetTracerImagesCount(int? tracerResponseId);
        // ApiGetTracerImagesCountAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiGetTracerImagesTempReturnModel> ApiGetTracerImagesTemp(int? tracerCustomId, int? userId);
        System.Collections.Generic.List<ApiGetTracerImagesTempReturnModel> ApiGetTracerImagesTemp(int? tracerCustomId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerImagesTempReturnModel>> ApiGetTracerImagesTempAsync(int? tracerCustomId, int? userId);

        System.Collections.Generic.List<ApiGetTracerQuestionInfoReturnModel> ApiGetTracerQuestionInfo(int? tracerCustomId, int? tracerQuestionId);
        System.Collections.Generic.List<ApiGetTracerQuestionInfoReturnModel> ApiGetTracerQuestionInfo(int? tracerCustomId, int? tracerQuestionId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerQuestionInfoReturnModel>> ApiGetTracerQuestionInfoAsync(int? tracerCustomId, int? tracerQuestionId);

        System.Collections.Generic.List<ApiGetTracerQuestionsReturnModel> ApiGetTracerQuestions(int? tracerId);
        System.Collections.Generic.List<ApiGetTracerQuestionsReturnModel> ApiGetTracerQuestions(int? tracerId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracerQuestionsReturnModel>> ApiGetTracerQuestionsAsync(int? tracerId);

        System.Collections.Generic.List<ApiGetTracersThatCanBeCopiedReturnModel> ApiGetTracersThatCanBeCopied(int? siteId, int? programId, int? userId);
        System.Collections.Generic.List<ApiGetTracersThatCanBeCopiedReturnModel> ApiGetTracersThatCanBeCopied(int? siteId, int? programId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracersThatCanBeCopiedReturnModel>> ApiGetTracersThatCanBeCopiedAsync(int? siteId, int? programId, int? userId);

        System.Collections.Generic.List<ApiGetTracersThatCanBeDeletedReturnModel> ApiGetTracersThatCanBeDeleted(int? siteId, int? programId, int? userId);
        System.Collections.Generic.List<ApiGetTracersThatCanBeDeletedReturnModel> ApiGetTracersThatCanBeDeleted(int? siteId, int? programId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetTracersThatCanBeDeletedReturnModel>> ApiGetTracersThatCanBeDeletedAsync(int? siteId, int? programId, int? userId);

        System.Collections.Generic.List<ApiGetUserPreferenceReturnModel> ApiGetUserPreference(int? userId, int? siteId, int? programId, string userPreferenceType);
        System.Collections.Generic.List<ApiGetUserPreferenceReturnModel> ApiGetUserPreference(int? userId, int? siteId, int? programId, string userPreferenceType, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUserPreferenceReturnModel>> ApiGetUserPreferenceAsync(int? userId, int? siteId, int? programId, string userPreferenceType);

        System.Collections.Generic.List<ApiGetUserRoleBySiteReturnModel> ApiGetUserRoleBySite(int? userId, int? siteId);
        System.Collections.Generic.List<ApiGetUserRoleBySiteReturnModel> ApiGetUserRoleBySite(int? userId, int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUserRoleBySiteReturnModel>> ApiGetUserRoleBySiteAsync(int? userId, int? siteId);

        System.Collections.Generic.List<ApiGetUsersReturnModel> ApiGetUsers(string lstUserIDs);
        System.Collections.Generic.List<ApiGetUsersReturnModel> ApiGetUsers(string lstUserIDs, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUsersReturnModel>> ApiGetUsersAsync(string lstUserIDs);

        System.Collections.Generic.List<ApiGetUsersDetailsReturnModel> ApiGetUsersDetails(string lstUserIDs, int? siteId);
        System.Collections.Generic.List<ApiGetUsersDetailsReturnModel> ApiGetUsersDetails(string lstUserIDs, int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUsersDetailsReturnModel>> ApiGetUsersDetailsAsync(string lstUserIDs, int? siteId);

        System.Collections.Generic.List<ApiGetUserSecurityAttributesReturnModel> ApiGetUserSecurityAttributes(int? userId, int? codeCategoryId, int? questionTyeId1, int? questionTyeId2);
        System.Collections.Generic.List<ApiGetUserSecurityAttributesReturnModel> ApiGetUserSecurityAttributes(int? userId, int? codeCategoryId, int? questionTyeId1, int? questionTyeId2, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUserSecurityAttributesReturnModel>> ApiGetUserSecurityAttributesAsync(int? userId, int? codeCategoryId, int? questionTyeId1, int? questionTyeId2);

        System.Collections.Generic.List<ApiGetUsersForAssignmentReturnModel> ApiGetUsersForAssignment(string searchString, string siteList);
        System.Collections.Generic.List<ApiGetUsersForAssignmentReturnModel> ApiGetUsersForAssignment(string searchString, string siteList, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGetUsersForAssignmentReturnModel>> ApiGetUsersForAssignmentAsync(string searchString, string siteList);

        int ApiGuestAccessSetupSave(int? siteId, bool? guestAccessFlag, bool? domainRestrictionFlag, string domainNames, int? userId);
        // ApiGuestAccessSetupSaveAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiGuestLinkReadReturnModel> ApiGuestLinkRead(int? siteId, int? tracerCustomId, int? programId, System.Guid? guestLinkGuid, int? guestLinkId);
        System.Collections.Generic.List<ApiGuestLinkReadReturnModel> ApiGuestLinkRead(int? siteId, int? tracerCustomId, int? programId, System.Guid? guestLinkGuid, int? guestLinkId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGuestLinkReadReturnModel>> ApiGuestLinkReadAsync(int? siteId, int? tracerCustomId, int? programId, System.Guid? guestLinkGuid, int? guestLinkId);

        System.Collections.Generic.List<ApiGuestUserTracerDetailSelectBySiteProgramReturnModel> ApiGuestUserTracerDetailSelectBySiteProgram(int? userId, int? siteId, int? programId, int? statusId);
        System.Collections.Generic.List<ApiGuestUserTracerDetailSelectBySiteProgramReturnModel> ApiGuestUserTracerDetailSelectBySiteProgram(int? userId, int? siteId, int? programId, int? statusId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiGuestUserTracerDetailSelectBySiteProgramReturnModel>> ApiGuestUserTracerDetailSelectBySiteProgramAsync(int? userId, int? siteId, int? programId, int? statusId);

        int ApiInsertGuestLinkAccessed(int? userId, System.Guid? guestLinkGuid);
        // ApiInsertGuestLinkAccessedAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiInsertQuestionImageMap(int? tracerQuestionId, int? tracerResponseId, string tempImageIDs, int? userId);
        // ApiInsertQuestionImageMapAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiInsertTracerTempImage(int? siteId, int? programId, int? tracerCustomId, int? tracerQuestionId, string imageName, int? userId);
        // ApiInsertTracerTempImageAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiLogicallyDeleteObservation(int? tracerResponseId, int? updatedById);
        // ApiLogicallyDeleteObservationAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiMenuStateGetReturnModel> ApiMenuStateGet(int? userId);
        System.Collections.Generic.List<ApiMenuStateGetReturnModel> ApiMenuStateGet(int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMenuStateGetReturnModel>> ApiMenuStateGetAsync(int? userId);

        int ApiMenuStateInit(int? userId, int? siteId, int? roleId, bool? accessToEdition, bool? accessToAmp, bool? accessToTracers, bool? accessToEramp, bool? accessToErTracers);
        // ApiMenuStateInitAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiMenuStateInitLocalDebug(int? userId);
        // ApiMenuStateInitLocalDebugAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiMenuStateProductsBySiteReturnModel> ApiMenuStateProductsBySite(string userLogonId);
        System.Collections.Generic.List<ApiMenuStateProductsBySiteReturnModel> ApiMenuStateProductsBySite(string userLogonId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMenuStateProductsBySiteReturnModel>> ApiMenuStateProductsBySiteAsync(string userLogonId);

        System.Collections.Generic.List<ApiMenuStateProductsBySiteAndProgramReturnModel> ApiMenuStateProductsBySiteAndProgram(int? userId);
        System.Collections.Generic.List<ApiMenuStateProductsBySiteAndProgramReturnModel> ApiMenuStateProductsBySiteAndProgram(int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMenuStateProductsBySiteAndProgramReturnModel>> ApiMenuStateProductsBySiteAndProgramAsync(int? userId);

        int ApiMenuStateSave(int? userId, int? siteId, int? userRoleId, int? programId, int? certificationItemId, bool? isCurrentCycle, string cycleEffectiveDate, string mockSurveyTitle, bool? accessToEdition, bool? accessToAmp, bool? accessToTracers, bool? accessToEramp, bool? accessToErTracers, bool? accessToCms, bool? accessToMockSurvey, bool? userIsMultiSiteAdmin);
        // ApiMenuStateSaveAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiMenuStateSaveArg(int? userId, string key, string value);
        // ApiMenuStateSaveArgAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiMenuStateSiteProgramDropdowns(int? userId);
        // ApiMenuStateSiteProgramDropdownsAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiMenuStateUpdate(int? userId);
        // ApiMenuStateUpdateAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdReturnModel> ApiMobileGetObservationDetailsById(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess);
        System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdReturnModel> ApiMobileGetObservationDetailsById(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdReturnModel>> ApiMobileGetObservationDetailsByIdAsync(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess);

        System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdWithValidationMessageReturnModel> ApiMobileGetObservationDetailsByIdWithValidationMessage(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess);
        System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdWithValidationMessageReturnModel> ApiMobileGetObservationDetailsByIdWithValidationMessage(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileGetObservationDetailsByIdWithValidationMessageReturnModel>> ApiMobileGetObservationDetailsByIdWithValidationMessageAsync(int? tracerCustomId, int? tracerResponseId, bool? isGuestAccess);

        System.Collections.Generic.List<ApiMobileGuestUserSelectProgramsBySiteReturnModel> ApiMobileGuestUserSelectProgramsBySite(int? userId, int? siteId, int? productId);
        System.Collections.Generic.List<ApiMobileGuestUserSelectProgramsBySiteReturnModel> ApiMobileGuestUserSelectProgramsBySite(int? userId, int? siteId, int? productId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileGuestUserSelectProgramsBySiteReturnModel>> ApiMobileGuestUserSelectProgramsBySiteAsync(int? userId, int? siteId, int? productId);

        System.Collections.Generic.List<ApiMobileGuestUserSelectSitesReturnModel> ApiMobileGuestUserSelectSites(int? userId, int? productId);
        System.Collections.Generic.List<ApiMobileGuestUserSelectSitesReturnModel> ApiMobileGuestUserSelectSites(int? userId, int? productId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileGuestUserSelectSitesReturnModel>> ApiMobileGuestUserSelectSitesAsync(int? userId, int? productId);

        System.Collections.Generic.List<ApiMobileResponsesSelectByTracerIdReturnModel> ApiMobileResponsesSelectByTracerId(int? tracerId, string responseStatusCsv);
        System.Collections.Generic.List<ApiMobileResponsesSelectByTracerIdReturnModel> ApiMobileResponsesSelectByTracerId(int? tracerId, string responseStatusCsv, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileResponsesSelectByTracerIdReturnModel>> ApiMobileResponsesSelectByTracerIdAsync(int? tracerId, string responseStatusCsv);

        System.Collections.Generic.List<ApiMobileSaveTracerResponseReturnModel> ApiMobileSaveTracerResponse(int? tracerId, int? observationId, string title, System.DateTime? observationDate, string medicalStaffInvolved, string staffInterviewed, int? observationsCount, string surveyTeam, string departmentId, string location, int? observationStatusId, int? tracerErrorValue, string note, int? userId, string medicalRecordNumber, string equipmentObserved, string contractedService, bool? isCalledByGuestAccess);
        System.Collections.Generic.List<ApiMobileSaveTracerResponseReturnModel> ApiMobileSaveTracerResponse(int? tracerId, int? observationId, string title, System.DateTime? observationDate, string medicalStaffInvolved, string staffInterviewed, int? observationsCount, string surveyTeam, string departmentId, string location, int? observationStatusId, int? tracerErrorValue, string note, int? userId, string medicalRecordNumber, string equipmentObserved, string contractedService, bool? isCalledByGuestAccess, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileSaveTracerResponseReturnModel>> ApiMobileSaveTracerResponseAsync(int? tracerId, int? observationId, string title, System.DateTime? observationDate, string medicalStaffInvolved, string staffInterviewed, int? observationsCount, string surveyTeam, string departmentId, string location, int? observationStatusId, int? tracerErrorValue, string note, int? userId, string medicalRecordNumber, string equipmentObserved, string contractedService, bool? isCalledByGuestAccess);

        System.Collections.Generic.List<ApiMobileTracerGetQuestionDetailReturnModel> ApiMobileTracerGetQuestionDetail(int? tracerCustomId, int? tracerQuestionId, int? tracerResponseId, int? userId);
        System.Collections.Generic.List<ApiMobileTracerGetQuestionDetailReturnModel> ApiMobileTracerGetQuestionDetail(int? tracerCustomId, int? tracerQuestionId, int? tracerResponseId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileTracerGetQuestionDetailReturnModel>> ApiMobileTracerGetQuestionDetailAsync(int? tracerCustomId, int? tracerQuestionId, int? tracerResponseId, int? userId);

        System.Collections.Generic.List<ApiMobileUpdateTracerQuestionAnswerReturnModel> ApiMobileUpdateTracerQuestionAnswer(int? observationId, int? userId, int? tracerQuestionId, int? tracerQuestionAnswerId, decimal? numerator, decimal? denominator, int? questionAnswer, int? questionNoteId, string questionNote);
        System.Collections.Generic.List<ApiMobileUpdateTracerQuestionAnswerReturnModel> ApiMobileUpdateTracerQuestionAnswer(int? observationId, int? userId, int? tracerQuestionId, int? tracerQuestionAnswerId, decimal? numerator, decimal? denominator, int? questionAnswer, int? questionNoteId, string questionNote, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileUpdateTracerQuestionAnswerReturnModel>> ApiMobileUpdateTracerQuestionAnswerAsync(int? observationId, int? userId, int? tracerQuestionId, int? tracerQuestionAnswerId, decimal? numerator, decimal? denominator, int? questionAnswer, int? questionNoteId, string questionNote);

        int ApiMobileUpdateTracerResponseStatus(int? tracerResponseId, int? tracerResponseStatusId);
        // ApiMobileUpdateTracerResponseStatusAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiMobileValidateGuestUserReturnModel> ApiMobileValidateGuestUser(string userLogin, int? siteId);
        System.Collections.Generic.List<ApiMobileValidateGuestUserReturnModel> ApiMobileValidateGuestUser(string userLogin, int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileValidateGuestUserReturnModel>> ApiMobileValidateGuestUserAsync(string userLogin, int? siteId);

        System.Collections.Generic.List<ApiMobileValidateTracerGuestUserReturnModel> ApiMobileValidateTracerGuestUser(string userLogin);
        System.Collections.Generic.List<ApiMobileValidateTracerGuestUserReturnModel> ApiMobileValidateTracerGuestUser(string userLogin, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMobileValidateTracerGuestUserReturnModel>> ApiMobileValidateTracerGuestUserAsync(string userLogin);

        System.Collections.Generic.List<ApiMsGetAllCorpSettingsByUserIdReturnModel> ApiMsGetAllCorpSettingsByUserId(int? userId);
        System.Collections.Generic.List<ApiMsGetAllCorpSettingsByUserIdReturnModel> ApiMsGetAllCorpSettingsByUserId(int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMsGetAllCorpSettingsByUserIdReturnModel>> ApiMsGetAllCorpSettingsByUserIdAsync(int? userId);

        System.Collections.Generic.List<ApiMsGetWorkFlowsReturnModel> ApiMsGetWorkFlows();
        System.Collections.Generic.List<ApiMsGetWorkFlowsReturnModel> ApiMsGetWorkFlows(out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMsGetWorkFlowsReturnModel>> ApiMsGetWorkFlowsAsync();

        int ApiMsUpdateWorkFlow(int? mockSurveyWorkFlowId, int? userId, string siteIDs);
        // ApiMsUpdateWorkFlowAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiMultisiteAuditInsert(int? tracerCustomId, int? siteId, int? userId, string msg);
        // ApiMultisiteAuditInsertAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiMultisiteCopyReturnModel> ApiMultisiteCopy(string selectedSites, int? tracerId, bool? isLocked, int? userId);
        System.Collections.Generic.List<ApiMultisiteCopyReturnModel> ApiMultisiteCopy(string selectedSites, int? tracerId, bool? isLocked, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMultisiteCopyReturnModel>> ApiMultisiteCopyAsync(string selectedSites, int? tracerId, bool? isLocked, int? userId);

        System.Collections.Generic.List<ApiMultisiteDeleteReturnModel> ApiMultisiteDelete(string sites, int? tracerId, int? userId);
        System.Collections.Generic.List<ApiMultisiteDeleteReturnModel> ApiMultisiteDelete(string sites, int? tracerId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMultisiteDeleteReturnModel>> ApiMultisiteDeleteAsync(string sites, int? tracerId, int? userId);

        System.Collections.Generic.List<ApiMultiSiteFindDifferencesReturnModel> ApiMultiSiteFindDifferences(int? parentId, int? childId, int? userId, bool? lockOnExactMatch);
        System.Collections.Generic.List<ApiMultiSiteFindDifferencesReturnModel> ApiMultiSiteFindDifferences(int? parentId, int? childId, int? userId, bool? lockOnExactMatch, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiMultiSiteFindDifferencesReturnModel>> ApiMultiSiteFindDifferencesAsync(int? parentId, int? childId, int? userId, bool? lockOnExactMatch);

        int ApiOptOutOfSystemTracers(int? tracerId, int? userId);
        // ApiOptOutOfSystemTracersAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiPublishTracer(int? tracerId, int? updatedById);
        // ApiPublishTracerAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiReAssignTask(string lstTaskIDs, int? assignedToUserId, string ccUserIDs, string dueDate, int? updatedByUserId);
        // ApiReAssignTaskAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiReportTracerObservationReturnModel> ApiReportTracerObservation(string customTracerIdFilter, out int? customSections);
        System.Collections.Generic.List<ApiReportTracerObservationReturnModel> ApiReportTracerObservation(string customTracerIdFilter, out int? customSections, out int procResult);
        // ApiReportTracerObservationAsync cannot be created due to having out parameters, or is relying on the procedure result (System.Collections.Generic.List<ApiReportTracerObservationReturnModel>)

        ApiReportTracerObservationDetailReturnModel ApiReportTracerObservationDetail(int? tracerResponseId, int? programId, int? cycleId, int? isErrorOnly, out int? customSections);
        // ApiReportTracerObservationDetailAsync cannot be created due to having out parameters, or is relying on the procedure result (ApiReportTracerObservationDetailReturnModel)

        System.Collections.Generic.List<ApiReportTracerObservationHeaderReturnModel> ApiReportTracerObservationHeader(int? tracerResponseId, int? siteId, int? programId);
        System.Collections.Generic.List<ApiReportTracerObservationHeaderReturnModel> ApiReportTracerObservationHeader(int? tracerResponseId, int? siteId, int? programId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiReportTracerObservationHeaderReturnModel>> ApiReportTracerObservationHeaderAsync(int? tracerResponseId, int? siteId, int? programId);

        System.Collections.Generic.List<ApiResponsesSelectByTracerIdReturnModel> ApiResponsesSelectByTracerId(int? tracerId, string responseStatusCsv);
        System.Collections.Generic.List<ApiResponsesSelectByTracerIdReturnModel> ApiResponsesSelectByTracerId(int? tracerId, string responseStatusCsv, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiResponsesSelectByTracerIdReturnModel>> ApiResponsesSelectByTracerIdAsync(int? tracerId, string responseStatusCsv);

        int ApiSaveSiteProgramPreference(int? userId, int? siteId, int? programId);
        // ApiSaveSiteProgramPreferenceAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiSaveTracerCategoryReturnModel> ApiSaveTracerCategory(int? tracerCategoryId, string tracerCategoryName, int? siteId, int? updatedById, bool? skipParentCategorySave);
        System.Collections.Generic.List<ApiSaveTracerCategoryReturnModel> ApiSaveTracerCategory(int? tracerCategoryId, string tracerCategoryName, int? siteId, int? updatedById, bool? skipParentCategorySave, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSaveTracerCategoryReturnModel>> ApiSaveTracerCategoryAsync(int? tracerCategoryId, string tracerCategoryName, int? siteId, int? updatedById, bool? skipParentCategorySave);

        System.Collections.Generic.List<ApiSelectGuestAccessDomainBySiteReturnModel> ApiSelectGuestAccessDomainBySite(int? siteId);
        System.Collections.Generic.List<ApiSelectGuestAccessDomainBySiteReturnModel> ApiSelectGuestAccessDomainBySite(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectGuestAccessDomainBySiteReturnModel>> ApiSelectGuestAccessDomainBySiteAsync(int? siteId);

        System.Collections.Generic.List<ApiSelectGuestAccessSettingsBySiteReturnModel> ApiSelectGuestAccessSettingsBySite(int? siteId);
        System.Collections.Generic.List<ApiSelectGuestAccessSettingsBySiteReturnModel> ApiSelectGuestAccessSettingsBySite(int? siteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectGuestAccessSettingsBySiteReturnModel>> ApiSelectGuestAccessSettingsBySiteAsync(int? siteId);

        System.Collections.Generic.List<ApiSelectProgramsBySiteReturnModel> ApiSelectProgramsBySite(int? userId, int? siteId, System.DateTime? standardEffBeginDate, int? productId);
        System.Collections.Generic.List<ApiSelectProgramsBySiteReturnModel> ApiSelectProgramsBySite(int? userId, int? siteId, System.DateTime? standardEffBeginDate, int? productId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectProgramsBySiteReturnModel>> ApiSelectProgramsBySiteAsync(int? userId, int? siteId, System.DateTime? standardEffBeginDate, int? productId);

        System.Collections.Generic.List<ApiSelectProgramsBySiteUserReturnModel> ApiSelectProgramsBySiteUser(int? siteId, System.DateTime? standardEffBeginDate, int? productId);
        System.Collections.Generic.List<ApiSelectProgramsBySiteUserReturnModel> ApiSelectProgramsBySiteUser(int? siteId, System.DateTime? standardEffBeginDate, int? productId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectProgramsBySiteUserReturnModel>> ApiSelectProgramsBySiteUserAsync(int? siteId, System.DateTime? standardEffBeginDate, int? productId);

        System.Collections.Generic.List<ApiSelectSiteAttributeMapReturnModel> ApiSelectSiteAttributeMap(int? siteId, string attributeList);
        System.Collections.Generic.List<ApiSelectSiteAttributeMapReturnModel> ApiSelectSiteAttributeMap(int? siteId, string attributeList, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectSiteAttributeMapReturnModel>> ApiSelectSiteAttributeMapAsync(int? siteId, string attributeList);

        System.Collections.Generic.List<ApiSelectTracerSiteByTracerCustomIdReturnModel> ApiSelectTracerSiteByTracerCustomId(int? tracerCustomId);
        System.Collections.Generic.List<ApiSelectTracerSiteByTracerCustomIdReturnModel> ApiSelectTracerSiteByTracerCustomId(int? tracerCustomId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectTracerSiteByTracerCustomIdReturnModel>> ApiSelectTracerSiteByTracerCustomIdAsync(int? tracerCustomId);

        System.Collections.Generic.List<ApiSelectUserByUserLogonIdReturnModel> ApiSelectUserByUserLogonId(string userLogonId);
        System.Collections.Generic.List<ApiSelectUserByUserLogonIdReturnModel> ApiSelectUserByUserLogonId(string userLogonId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSelectUserByUserLogonIdReturnModel>> ApiSelectUserByUserLogonIdAsync(string userLogonId);

        System.Collections.Generic.List<ApiSetDefaultTracerCategoryForSiteReturnModel> ApiSetDefaultTracerCategoryForSite(int? tracerCategoryId, int? siteId, int? updatedById);
        System.Collections.Generic.List<ApiSetDefaultTracerCategoryForSiteReturnModel> ApiSetDefaultTracerCategoryForSite(int? tracerCategoryId, int? siteId, int? updatedById, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSetDefaultTracerCategoryForSiteReturnModel>> ApiSetDefaultTracerCategoryForSiteAsync(int? tracerCategoryId, int? siteId, int? updatedById);

        System.Collections.Generic.List<ApiSitesNoLongerAuthorizedToAccessReturnModel> ApiSitesNoLongerAuthorizedToAccess(int? tracerId, int? userId);
        System.Collections.Generic.List<ApiSitesNoLongerAuthorizedToAccessReturnModel> ApiSitesNoLongerAuthorizedToAccess(int? tracerId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiSitesNoLongerAuthorizedToAccessReturnModel>> ApiSitesNoLongerAuthorizedToAccessAsync(int? tracerId, int? userId);

        System.Collections.Generic.List<ApiTracerDetailSelectBySiteProgramStatusReturnModel> ApiTracerDetailSelectBySiteProgramStatus(int? siteId, int? programId, int? statusId);
        System.Collections.Generic.List<ApiTracerDetailSelectBySiteProgramStatusReturnModel> ApiTracerDetailSelectBySiteProgramStatus(int? siteId, int? programId, int? statusId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiTracerDetailSelectBySiteProgramStatusReturnModel>> ApiTracerDetailSelectBySiteProgramStatusAsync(int? siteId, int? programId, int? statusId);

        System.Collections.Generic.List<ApiTracersBySiteProgramStatusReturnModel> ApiTracersBySiteProgramStatus(int? siteId, int? programId, int? statusId, int? userId);
        System.Collections.Generic.List<ApiTracersBySiteProgramStatusReturnModel> ApiTracersBySiteProgramStatus(int? siteId, int? programId, int? statusId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiTracersBySiteProgramStatusReturnModel>> ApiTracersBySiteProgramStatusAsync(int? siteId, int? programId, int? statusId, int? userId);

        System.Collections.Generic.List<ApiUnlockedMasterValidationReturnModel> ApiUnlockedMasterValidation(int? tracerId, int? userId);
        System.Collections.Generic.List<ApiUnlockedMasterValidationReturnModel> ApiUnlockedMasterValidation(int? tracerId, int? userId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiUnlockedMasterValidationReturnModel>> ApiUnlockedMasterValidationAsync(int? tracerId, int? userId);

        int ApiUnpublishTracer(int? tracerId, int? updatedById);
        // ApiUnpublishTracerAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiUpdateSelectPasscodeReturnModel> ApiUpdateSelectPasscode(int? userId, int? createdByUserId, int? passcode);
        System.Collections.Generic.List<ApiUpdateSelectPasscodeReturnModel> ApiUpdateSelectPasscode(int? userId, int? createdByUserId, int? passcode, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiUpdateSelectPasscodeReturnModel>> ApiUpdateSelectPasscodeAsync(int? userId, int? createdByUserId, int? passcode);

        int ApiUpdateSiteEmailNotificationSettings(int? siteId, bool? sendEmailOnTaskCreation, bool? sendEmailBeforeTaskDue, int? daysBeforeTaskDue, bool? sendEmailsAfterTaskDue, int? daysAfterTaskDue, bool? sendRemainderEmailAfterTaskDue, bool? sendTaskReportToCc, int? taskReportToCcScheduleTypeId, bool? sendTaskReportToUsers, int? taskReportToUsersScheduleTypeId, string taskReportRecipients, bool? sendEmailOnAssigningEp, int? taskDueRecipientType, int? updatedByUserId);
        // ApiUpdateSiteEmailNotificationSettingsAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiUpdateTaskObservationAssoc(int? tracerResponseId, string taskIDs);
        // ApiUpdateTaskObservationAssocAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiUpdateTracerCategoryForTracer(int? tracerCategoryId, int? tracerCustomId, int? updatedById);
        // ApiUpdateTracerCategoryForTracerAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiUpdateTracerQuestionAnswerReturnModel> ApiUpdateTracerQuestionAnswer(int? tracerQuestionId, int? tracerResponseId, int? userId, string questionNote, string questionNoteId);
        System.Collections.Generic.List<ApiUpdateTracerQuestionAnswerReturnModel> ApiUpdateTracerQuestionAnswer(int? tracerQuestionId, int? tracerResponseId, int? userId, string questionNote, string questionNoteId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiUpdateTracerQuestionAnswerReturnModel>> ApiUpdateTracerQuestionAnswerAsync(int? tracerQuestionId, int? tracerResponseId, int? userId, string questionNote, string questionNoteId);

        int ApiUpdateTracerStatusHistory(int? tracerCustomId, int? tracerStatusId, int? userId);
        // ApiUpdateTracerStatusHistoryAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int ApiUpdateUserPreference(int? userId, int? siteId, int? programId, string userPreferenceType, string preferenceValue);
        // ApiUpdateUserPreferenceAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ApiUpdateUserTaskReturnModel> ApiUpdateUserTask(int? taskId, string taskName, int? taskTypeId, int? siteId, int? programId, string assignedDate, int? assignedToUserId, int? assignedByUserId, string taskDetails, string ccUserIDs, string dueDate, int? taskStatus, int? updatedByUserId, int? createdByUserId, int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, int? tracerQuestionAnswerId, int? epTextId, int? cmsStandardId, bool? reminderEmailRequired, string taskResolution, string completeDate, string lstUsers);
        System.Collections.Generic.List<ApiUpdateUserTaskReturnModel> ApiUpdateUserTask(int? taskId, string taskName, int? taskTypeId, int? siteId, int? programId, string assignedDate, int? assignedToUserId, int? assignedByUserId, string taskDetails, string ccUserIDs, string dueDate, int? taskStatus, int? updatedByUserId, int? createdByUserId, int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, int? tracerQuestionAnswerId, int? epTextId, int? cmsStandardId, bool? reminderEmailRequired, string taskResolution, string completeDate, string lstUsers, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ApiUpdateUserTaskReturnModel>> ApiUpdateUserTaskAsync(int? taskId, string taskName, int? taskTypeId, int? siteId, int? programId, string assignedDate, int? assignedToUserId, int? assignedByUserId, string taskDetails, string ccUserIDs, string dueDate, int? taskStatus, int? updatedByUserId, int? createdByUserId, int? tracerCustomId, int? tracerResponseId, int? tracerQuestionId, int? tracerQuestionAnswerId, int? epTextId, int? cmsStandardId, bool? reminderEmailRequired, string taskResolution, string completeDate, string lstUsers);

    }

}
// </auto-generated>
