// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiCodeSelectByIdReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel1
        {
            public System.Int32 CodeID { get; set; }
            public System.Int32 CodeCategoryID { get; set; }
            public System.Int32 ParentID { get; set; }
            public System.String CodeValue { get; set; }
            public System.String DecodeValue { get; set; }
            public System.Int32 SortOrder { get; set; }
            public System.Boolean Active { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel2
        {
            public System.Int32 CodeID { get; set; }
            public System.Int32 CodeCategoryID { get; set; }
            public System.Int32 ParentID { get; set; }
            public System.String CodeValue { get; set; }
            public System.String DecodeValue { get; set; }
            public System.Int32 SortOrder { get; set; }
            public System.Boolean Active { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel3
        {
            public System.Int32 CodeID { get; set; }
            public System.Int32 CodeCategoryID { get; set; }
            public System.Int32 ParentID { get; set; }
            public System.String CodeValue { get; set; }
            public System.String DecodeValue { get; set; }
            public System.Int32 SortOrder { get; set; }
            public System.Boolean Active { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel3> ResultSet3;

    }

}
// </auto-generated>
