// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiCreateTracersGuestUserReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel1
        {
            public System.Int32 UserID { get; set; }
            public System.String FirstName { get; set; }
            public System.String LastName { get; set; }
            public System.String MiddleName { get; set; }
            public System.String UserLogonID { get; set; }
            public System.Int16 UserStatus { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel2
        {
            public System.Int32 UserId { get; set; }
            public System.Int32 SiteID { get; set; }
            public System.Int32 RoleID { get; set; }
            public System.Boolean? TracersAccess { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel3
        {
            public System.Int32 SiteID { get; set; }
            public System.String SiteName { get; set; }
            public System.Boolean SiteStatus { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel3> ResultSet3;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel4
        {
            public System.Int32? IsEulaAccepted { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel4> ResultSet4;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel5
        {
            public System.Int32? IsGlobalAdmin { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel5> ResultSet5;

    }

}
// </auto-generated>
