// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetUsersForAssignmentReturnModel
    {
        public System.Int32 UserID { get; set; }
        public System.String EmailAddress { get; set; }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public System.Boolean? IsExternal { get; set; }
        public System.String UserRole { get; set; }
    }

}
// </auto-generated>
