// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetTracersThatCanBeCopiedReturnModel
    {
        public System.Int32? GroupID { get; set; }
        public System.Int32 TracerID { get; set; }
        public System.String TracerName { get; set; }
        public System.String TracerType { get; set; }
        public System.Boolean? IsLocked { get; set; }
        public System.String InMultipleSites { get; set; }
        public System.Boolean? MustOptOutToEdit { get; set; }
    }

}
// </auto-generated>
