// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetSiteEmailNotificationSettingsReturnModel
    {
        public System.Int32? SiteID { get; set; }
        public System.Boolean? SendEmailOnTaskCreation { get; set; }
        public System.Boolean? SendEmailBeforeTaskDue { get; set; }
        public System.Int32? DaysBeforeTaskDue { get; set; }
        public System.Boolean? SendEmailsAfterTaskDue { get; set; }
        public System.Int32? DaysAfterTaskDue { get; set; }
        public System.Boolean? SendRemainderEmailAfterTaskDue { get; set; }
        public System.Boolean? SendTaskReportToCC { get; set; }
        public System.Int32? TaskReportToCCScheduleTypeID { get; set; }
        public System.Boolean? SendTaskReportToUsers { get; set; }
        public System.Int32? TaskReportToUsersScheduleTypeID { get; set; }
        public System.String TaskReportRecipients { get; set; }
        public System.Boolean? SendEmailOnAssigningEP { get; set; }
        public System.Int32? TaskDueRecipientType { get; set; }
    }

}
// </auto-generated>
