// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetTaskListReturnModel
    {
        public System.Int32 TaskID { get; set; }
        public System.String TaskName { get; set; }
        public System.Int32? TaskTypeID { get; set; }
        public System.String TaskDetails { get; set; }
        public System.Int32? SiteID { get; set; }
        public System.Int32? ProgramID { get; set; }
        public System.Int32? TracerCustomID { get; set; }
        public System.Int32? TracerResponseID { get; set; }
        public System.String TracerName { get; set; }
        public System.Int32? TracerQuestionAnswerID { get; set; }
        public System.Int32? TracerQuestionID { get; set; }
        public System.String Std { get; set; }
        public System.Int32? CMSStandardID { get; set; }
        public System.String AssignedToUserName { get; set; }
        public System.String AssignedByUserName { get; set; }
        public System.Int32? AssignedToUserID { get; set; }
        public System.Int32? AssignedByUserID { get; set; }
        public System.DateTime? DueDate { get; set; }
        public System.Int32? TaskStatus { get; set; }
        public System.String StatusName { get; set; }
    }

}
// </auto-generated>
