// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetTaskDetailsForSendingEmailReturnModel
    {
        public System.Int32 TaskID { get; set; }
        public System.String TaskName { get; set; }
        public System.Int32 TaskTypeID { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.String SiteName { get; set; }
        public System.Int32 HCOID { get; set; }
        public System.Int32 ProgramID { get; set; }
        public System.Int32 TracerCustomID { get; set; }
        public System.Int32 TracerResponseID { get; set; }
        public System.Int32 TracerQuestionID { get; set; }
        public System.Int32 TracerQuestionAnswerID { get; set; }
        public System.Int32 EPTextID { get; set; }
        public System.Int32 CMSStandardID { get; set; }
        public System.String AssignedOn { get; set; }
        public System.String DueDate { get; set; }
        public System.String CompletionDate { get; set; }
        public System.Int32 AssignedToUserID { get; set; }
        public System.Int32 AssignedByUserID { get; set; }
        public System.Int32 UpdatedByUserID { get; set; }
        public System.Int32 CreatedByUserID { get; set; }
        public System.String AssignedByFirstName { get; set; }
        public System.String AssignedByLastName { get; set; }
        public System.String AssignedToFirstName { get; set; }
        public System.String AssignedToLastName { get; set; }
        public System.String UpdatedByFirstName { get; set; }
        public System.String UpdatedByLastName { get; set; }
        public System.String CreatedByFirstName { get; set; }
        public System.String CreatedByLastName { get; set; }
        public System.String AssignedByEmail { get; set; }
        public System.String AssignedToEmail { get; set; }
        public System.String UpdatedByEmail { get; set; }
        public System.String CreatedByEmail { get; set; }
        public System.String TaskDetails { get; set; }
        public System.String CCUserIDs { get; set; }
        public System.Int32 TaskStatus { get; set; }
        public System.String TaskStatusName { get; set; }
        public System.Boolean ReminderEmailRequired { get; set; }
        public System.String CompletionDetails { get; set; }
        public System.String TaskLinkUrl { get; set; }
        public System.String ItemAssociated { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.String ProgramName { get; set; }
    }

}
// </auto-generated>
