// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetTargetSitesForCopyReturnModel
    {
        public System.Int32? GroupID { get; set; }
        public System.Int32? TracerID { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.String TracerStatus { get; set; }
        public System.Int32? Responses { get; set; }
        public System.String SiteName { get; set; }
        public System.Boolean? IsLocked { get; set; }
        public System.Boolean? HasTracerWithSameName { get; set; }
    }

}
// </auto-generated>
