// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetTaskLinkDetailsReturnModel
    {
        public System.Guid TaskLinkGUID { get; set; }
        public System.Int32 TaskID { get; set; }
        public System.Int32 TaskStatus { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.String SiteName { get; set; }
        public System.Int32 ProgramID { get; set; }
        public System.String ProgramName { get; set; }
        public System.Int32 AssignedToUserID { get; set; }
        public System.String UserEmailId { get; set; }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public System.Int16 UserStatus { get; set; }
        public System.Int32? UserRole { get; set; }
        public System.Int32 TaskTypeID { get; set; }
        public System.Int32? ActualTaskType { get; set; }
        public System.Boolean IsSiteActive { get; set; }
        public System.Boolean? IsLicenseExpired { get; set; }
        public System.Int32? IsEulaAccepted { get; set; }
    }

}
// </auto-generated>
