// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGuestUserTracerDetailSelectBySiteProgramReturnModel
    {
        public System.Int32 TracerCustomID { get; set; }
        public System.String TracerCustomName { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.Int32 ProgramID { get; set; }
        public System.Int32 TracerCategoryID { get; set; }
        public System.String TracerCategoryCode { get; set; }
        public System.String TracerCategoryName { get; set; }
        public System.Int32? NumOfResponses { get; set; }
        public System.Int32 TracerStatusID { get; set; }
        public System.String TracerStatusCode { get; set; }
        public System.String TracerStatusName { get; set; }
        public System.Int32 CreatedByID { get; set; }
        public System.Int32 UpdatedByID { get; set; }
        public System.String UpdateUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.String TracerType { get; set; }
    }

}
// </auto-generated>
