// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetCategoryNamesReturnModel
    {
        public System.Int32 OrganizationTypeID { get; set; }
        public System.Int32 ProgramID { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.String Title { get; set; }
        public System.Int32 Ranking { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32 CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Int32 UpdatedByID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }

}
// </auto-generated>
