// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiGetDepartmentHierarchyByRankIdReturnModel
    {
        public System.Int32 OrganizationID { get; set; }
        public System.Int32? ParentOrganizationID { get; set; }
        public System.Int32? OrganizationHierarchyID { get; set; }
        public System.Int32? ParentHierarchyID { get; set; }
        public System.String OrganizationTitle { get; set; }
        public System.String OrganizationTypeTitle { get; set; }
        public System.Boolean OrganizationTypeActive { get; set; }
        public System.Boolean OrganizationActive { get; set; }
        public System.Int32 Ranking { get; set; }
    }

}
// </auto-generated>
