// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMobileTracerGetQuestionDetailReturnModel
    {
        public System.String QuestionText { get; set; }
        public System.Int32? IsResponseMandatory { get; set; }
        public System.String QuestionNo { get; set; }
        public System.Int32 TracerQuestionAnswerID { get; set; }
        public System.Int32? Num { get; set; }
        public System.Int32? Den { get; set; }
        public System.Boolean? IsNotApplicable { get; set; }
        public System.Int32? QuestionNoteID { get; set; }
        public System.String Note { get; set; }
    }

}
// </auto-generated>
