// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMobileResponsesSelectByTracerIdReturnModel
    {
        public System.Int32 TracerResponseID { get; set; }
        public System.Int32 TracerCustomID { get; set; }
        public System.String TracerResponseTitle { get; set; }
        public System.Int32 ResponseStatusID { get; set; }
        public System.String ResponseStatusName { get; set; }
        public System.Int32 CreatedByID { get; set; }
    }

}
// </auto-generated>
