// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMenuStateGetReturnModel
    {
        public System.Int32 UserID { get; set; }
        public System.Int32 SiteID { get; set; }
        public System.String SiteName { get; set; }
        public System.Int32 UserRoleID { get; set; }
        public System.Int32 ProgramID { get; set; }
        public System.String ProgramName { get; set; }
        public System.Int32 CertificationItemID { get; set; }
        public System.Boolean IsCurrentCycle { get; set; }
        public System.String CycleEffectiveDate { get; set; }
        public System.String MockSurveyTitle { get; set; }
        public System.Boolean AccessToEdition { get; set; }
        public System.Boolean AccessToAMP { get; set; }
        public System.Boolean AccessToTracers { get; set; }
        public System.Boolean AccessToERAMP { get; set; }
        public System.Boolean AccessToERTracers { get; set; }
        public System.Boolean AccessToCMS { get; set; }
        public System.Boolean AccessToMockSurvey { get; set; }
        public System.Boolean UserIsMultiSiteAdmin { get; set; }
        public System.Int32 CycleID { get; set; }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public System.String UserLogonID { get; set; }
        public System.Int32 ProgramGroupTypeID { get; set; }
    }

}
// </auto-generated>
