// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMsGetAllCorpSettingsByUserIdReturnModel
    {
        public System.String Group { get; set; }
        public System.Int32 SiteId { get; set; }
        public System.String HCOID { get; set; }
        public System.String SiteName { get; set; }
        public System.String ExpirationDate { get; set; }
        public System.String LicenseStatus { get; set; }
        public System.Int32? MockSurveyWorkFlowID { get; set; }
        public System.String WorkFlowName { get; set; }
        public System.String PreviousWorkFlow { get; set; }
        public System.String RecommendationRequired { get; set; }
        public System.String UpdateDate { get; set; }
        public System.String UpdatedBy { get; set; }
    }

}
// </auto-generated>
