// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMobileValidateGuestUserReturnModel
    {
        public System.Int32? UserID { get; set; }
        public System.String EmailAddress { get; set; }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public System.Boolean? IsUserActive { get; set; }
        public System.Boolean? IsUserSiteMapPresent { get; set; }
        public System.Int32? IsEulaAccepted { get; set; }
        public System.Boolean? IsGlobalAdmin { get; set; }
        public System.Boolean? IsNewUser { get; set; }
        public System.Boolean? IsRegisteredUser { get; set; }
        public System.Int32? SiteID { get; set; }
        public System.String SiteName { get; set; }
        public System.Int32? HCOID { get; set; }
        public System.Int32? RoleID { get; set; }
        public System.Boolean? IsTracersAccess { get; set; }
        public System.Boolean? IsSiteActive { get; set; }
    }

}
// </auto-generated>
