// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiMobileGetObservationDetailsByIdWithValidationMessageReturnModel
    {
        public System.Int32? SortOrder { get; set; }
        public System.Int32 TracerQuestionID { get; set; }
        public System.Int32 TracerQuestionAnswerID { get; set; }
        public System.String QuestionText { get; set; }
        public System.Boolean? IsScored { get; set; }
        public System.Boolean? IsResponseRequired { get; set; }
        public System.Int32? ObservationID { get; set; }
        public System.Int32? SectionSortOrder { get; set; }
        public System.String Section { get; set; }
        public System.Int32? TracerTypeID { get; set; }
        public System.String ErrorMessage { get; set; }
        public System.Int32? ErrorCode { get; set; }
    }

}
// </auto-generated>
