// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiReportTracerObservationDetailReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel1
        {
            public System.Int32 TracerResponseID { get; set; }
            public System.Int32 SortOrder { get; set; }
            public System.Int32 TracerQuestionID { get; set; }
            public System.Int32 TracerQuestionAnswerID { get; set; }
            public System.String QuestionText { get; set; }
            public System.Decimal? Numerator { get; set; }
            public System.Decimal? Denominator { get; set; }
            public System.Decimal? CompliancePercent { get; set; }
            public System.Decimal? NumValid { get; set; }
            public System.Decimal? DenValid { get; set; }
            public System.Boolean IsResponseMandatory { get; set; }
            public System.Int32? QuestionAnswer { get; set; }
            public System.Boolean FollowUpRequired { get; set; }
            public System.String StandardEP { get; set; }
            public System.String TagCoP { get; set; }
            public System.String SectionName { get; set; }
            public System.Int32? SectionSortOrder { get; set; }
            public System.Int32? TracerQuestionCategoryID { get; set; }
            public System.String QuestionNote { get; set; }
            public System.Int32? CustomSections { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel2
        {
            public System.Int32 TracerQuestionID { get; set; }
            public System.String FileName { get; set; }
            public System.Int32 SiteID { get; set; }
            public System.Int32 ProgramID { get; set; }
            public System.Int32 TracerCustomID { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
