// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiReportTracerObservationHeaderReturnModel
    {
        public System.String TracerCustomName { get; set; }
        public System.String TracerCategoryName { get; set; }
        public System.String TracerResponseTitle { get; set; }
        public System.String DepartmentName { get; set; }
        public System.String BuildingName { get; set; }
        public System.String CampusName { get; set; }
        public System.String SurveyTeam { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.String MedicalStaffInvolved { get; set; }
        public System.String StaffInterviewed { get; set; }
        public System.String Location { get; set; }
        public System.String MedicalRecordNumber { get; set; }
        public System.String EquipmentObserved { get; set; }
        public System.String ContractedService { get; set; }
        public System.String TracerNote { get; set; }
        public System.Int32 ResponseStatusID { get; set; }
        public System.Int32 TracerTypeID { get; set; }
        public System.Int32 ObservationsCount { get; set; }
    }

}
// </auto-generated>
