// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiReportTracerObservationReturnModel
    {
        public System.Int32 TracerCustomID { get; set; }
        public System.String TracerCustomName { get; set; }
        public System.String QuestionText { get; set; }
        public System.Int32 SortOrder { get; set; }
        public System.Boolean IsResponseMandatory { get; set; }
        public System.String SectionName { get; set; }
        public System.Int32? SectionSortOrder { get; set; }
        public System.Int32? TracerQuestionCategoryID { get; set; }
        public System.Int32? CustomSections { get; set; }
    }

}
// </auto-generated>
