// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ApiSelectProgramsBySiteUserReturnModel
    {
        public System.Int32? ProgramID { get; set; }
        public System.String ProgramCode { get; set; }
        public System.String ProgramName { get; set; }
        public System.Int32? ProductID { get; set; }
        public System.String AdvCertFlag { get; set; }
        public System.Int32? AdvCertListTypeID { get; set; }
        public System.String CertProgramName { get; set; }
        public System.Int64? SortOrder { get; set; }
        public System.Int32? BaseProgramID { get; set; }
        public System.Int32? IsCmsLicenseActive { get; set; }
    }

}
// </auto-generated>
