// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    // Site
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Site
    {
        public int SiteId { get; set; } // SiteID (Primary key)
        public string SiteName { get; set; } // SiteName (length: 75)
        public bool Status { get; set; } // Status
        public System.DateTime? ExpirationDate { get; set; } // ExpirationDate
        public bool ParentSite { get; set; } // ParentSite
        public int ParentId { get; set; } // ParentID
        public int? Hcoid { get; set; } // HCOID
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public bool VaFlag { get; set; } // VAFlag
        public bool IsRetainSiteName { get; set; } // IsRetainSiteName
        public int? UpdatedByUserId { get; set; } // UpdatedByUserID

        // Reverse navigation

        /// <summary>
        /// Child UserSiteMaps where [UserSiteMap].[SiteId] point to this entity (FK_UserSiteMap_Site)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserSiteMap> UserSiteMaps { get; set; } // UserSiteMap.FK_UserSiteMap_Site

        public Site()
        {
            CreateDate = System.DateTime.Now;
            UpdateDate = System.DateTime.Now;
            VaFlag = false;
            IsRetainSiteName = false;
            UserSiteMaps = new System.Collections.Generic.List<UserSiteMap>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
