// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    // Token
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Token
    {
        public int TokenId { get; set; } // TokenID (Primary key)
        public int UserId { get; set; } // UserID
        public string AuthToken { get; set; } // AuthToken (length: 250)
        public System.DateTime IssuedOn { get; set; } // IssuedOn
        public System.DateTime ExpiresOn { get; set; } // ExpiresOn
        public string LatestPortalSessionId { get; set; } // LatestPortalSessionID (length: 100)
        public bool IsAmpAccessed { get; set; } // IsAMPAccessed
        public bool IsTracersAccessed { get; set; } // IsTracersAccessed

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Token].([UserId]) (FK_Tokens_User)
        /// </summary>
        public virtual User User { get; set; } // FK_Tokens_User

        public Token()
        {
            IsAmpAccessed = false;
            IsTracersAccessed = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
