// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class User
    {
        public int UserId { get; set; } // UserID (Primary key)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public string MiddleName { get; set; } // MiddleName (length: 50)
        public string UserLogonId { get; set; } // UserLogonID (length: 100)
        public short Status { get; set; } // Status
        public System.DateTime? ExpirationDate { get; set; } // ExpirationDate
        public int? CreatedByUserId { get; set; } // CreatedByUserID
        public int? UpdatedByUserId { get; set; } // UpdatedByUserID
        public System.DateTime? UpdateDateByUser { get; set; } // UpdateDateByUser
        public int? UpdatedByGlobalAdminUserId { get; set; } // UpdatedByGlobalAdminUserID
        public System.DateTime? UpdateDateByGlobalAdmin { get; set; } // UpdateDateByGlobalAdmin
        public System.Guid UserGuid { get; set; } // UserGUID
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string MobilePhone { get; set; } // MobilePhone (length: 10)
        public bool IsPhoneVerified { get; set; } // IsPhoneVerified

        // Reverse navigation

        /// <summary>
        /// Child Tokens where [Token].[UserID] point to this entity (FK_Tokens_User)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Token> Tokens { get; set; } // Token.FK_Tokens_User
        /// <summary>
        /// Child UserSecurityAttributes where [UserSecurityAttribute].[UserID] point to this entity (FK_UserSecurityAttribute_User)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserSecurityAttribute> UserSecurityAttributes { get; set; } // UserSecurityAttribute.FK_UserSecurityAttribute_User
        /// <summary>
        /// Child UserSiteMaps where [UserSiteMap].[UserId] point to this entity (FK_UserSiteMap_User)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserSiteMap> UserSiteMaps { get; set; } // UserSiteMap.FK_UserSiteMap_User

        public User()
        {
            UserGuid = System.Guid.NewGuid();
            CreateDate = System.DateTime.Now;
            UpdateDate = System.DateTime.Now;
            MobilePhone = "";
            IsPhoneVerified = false;
            Tokens = new System.Collections.Generic.List<Token>();
            UserSecurityAttributes = new System.Collections.Generic.List<UserSecurityAttribute>();
            UserSiteMaps = new System.Collections.Generic.List<UserSiteMap>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
