// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    // UserSecurityAttribute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class UserSecurityAttribute
    {
        public int UserId { get; set; } // UserID (Primary key)
        public int AttributeTypeId { get; set; } // AttributeTypeID (Primary key)
        public string AttributeValue { get; set; } // AttributeValue (length: 250)
        public System.DateTime? AttributeActivationDate { get; set; } // AttributeActivationDate
        public System.DateTime? AttributeExpirationDate { get; set; } // AttributeExpirationDate
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public System.DateTime? UpdateDate { get; set; } // UpdateDate

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [UserSecurityAttribute].([UserId]) (FK_UserSecurityAttribute_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserSecurityAttribute_User

        public UserSecurityAttribute()
        {
            CreateDate = System.DateTime.Now;
            UpdateDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
