// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class UsmMsRetrieveFileReturnModel
    {
        public System.Guid stream_id { get; set; }
        public System.Byte[] file_stream { get; set; }
        public System.String name { get; set; }
        public Microsoft.SqlServer.Types.SqlHierarchyId path_locator { get; set; }
        public Microsoft.SqlServer.Types.SqlHierarchyId? parent_path_locator { get; set; }
        public System.String file_type { get; set; }
        public System.Int64? cached_file_size { get; set; }
        public System.DateTimeOffset creation_time { get; set; }
        public System.DateTimeOffset last_write_time { get; set; }
        public System.DateTimeOffset? last_access_time { get; set; }
        public System.Boolean is_directory { get; set; }
        public System.Boolean is_offline { get; set; }
        public System.Boolean is_hidden { get; set; }
        public System.Boolean is_readonly { get; set; }
        public System.Boolean is_archive { get; set; }
        public System.Boolean is_system { get; set; }
        public System.Boolean is_temporary { get; set; }
    }

}
// </auto-generated>
