// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class UspSiteSelectReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel1
        {
            public System.Int32 SiteID { get; set; }
            public System.String SiteName { get; set; }
            public System.Boolean Status { get; set; }
            public System.DateTime? ExpirationDate { get; set; }
            public System.Boolean ParentSite { get; set; }
            public System.Int32 ParentID { get; set; }
            public System.Int32? HCOID { get; set; }
            public System.Boolean IsRetainSiteName { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel2
        {
            public System.Int32 SiteID { get; set; }
            public System.String SiteName { get; set; }
            public System.Boolean Status { get; set; }
            public System.DateTime? ExpirationDate { get; set; }
            public System.Boolean ParentSite { get; set; }
            public System.Int32 ParentID { get; set; }
            public System.Int32? HCOID { get; set; }
            public System.Boolean IsRetainSiteName { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
