

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Jcr.Api\Web.config"
//     Connection String Name: "DBMEdition01"
//     Connection String:      "server=JCRDEVESQL01\JCRDEVEXTRA01;database=DBMEdition01_Dev;User ID=Grace;password=**zapped**;;ApplicationIntent=ReadWrite"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition: Core-based Licensing (64-bit)
// Database Engine Edition: Enterprise

