// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{
    using Jcr.Data;

    // Site
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class SiteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Site>
    {
        public SiteConfiguration()
            : this("dbo")
        {
        }

        public SiteConfiguration(string schema)
        {
            ToTable("Site", schema);
            HasKey(x => x.SiteId);

            Property(x => x.SiteId).HasColumnName(@"SiteID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SiteName).HasColumnName(@"SiteName").HasColumnType("nvarchar").IsRequired().HasMaxLength(75);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bit").IsRequired();
            Property(x => x.ExpirationDate).HasColumnName(@"ExpirationDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ParentSite).HasColumnName(@"ParentSite").HasColumnType("bit").IsRequired();
            Property(x => x.ParentId).HasColumnName(@"ParentID").HasColumnType("int").IsRequired();
            Property(x => x.Hcoid).HasColumnName(@"HCOID").HasColumnType("int").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.VaFlag).HasColumnName(@"VAFlag").HasColumnType("bit").IsRequired();
            Property(x => x.IsRetainSiteName).HasColumnName(@"IsRetainSiteName").HasColumnType("bit").IsRequired();
            Property(x => x.UpdatedByUserId).HasColumnName(@"UpdatedByUserID").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
