// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Jcr.Data
{
    using Jcr.Data;

    // Token
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class TokenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Token>
    {
        public TokenConfiguration()
            : this("dbo")
        {
        }

        public TokenConfiguration(string schema)
        {
            ToTable("Token", schema);
            HasKey(x => x.TokenId);

            Property(x => x.TokenId).HasColumnName(@"TokenID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            Property(x => x.AuthToken).HasColumnName(@"AuthToken").HasColumnType("nvarchar").IsRequired().HasMaxLength(250);
            Property(x => x.IssuedOn).HasColumnName(@"IssuedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.ExpiresOn).HasColumnName(@"ExpiresOn").HasColumnType("datetime").IsRequired();
            Property(x => x.LatestPortalSessionId).HasColumnName(@"LatestPortalSessionID").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.IsAmpAccessed).HasColumnName(@"IsAMPAccessed").HasColumnType("bit").IsRequired();
            Property(x => x.IsTracersAccessed).HasColumnName(@"IsTracersAccessed").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.Tokens).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_Tokens_User
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
